[package]
name = "roguelike_tutorial"
version = "0.1.0"
authors = ["Diego Kennedy"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rltk = { version = "0.8.0" }
